api_version = "2026-07"

[[extensions]]
name = "ReturnFast Returns"
handle = "returnfast-customer-account"
uid = "b4b5d5ab-3cef-1919-80ed-c30c98eee06a7be3d1fd"
type = "ui_extension"

[extensions.capabilities]
api_access = true
network_access = true

[extensions.returnfast]
customer_portal_url = "http://localhost:5173"
laravel_api_url = "https://api-local.returnfast.net"

[[extensions.targeting]]
target = "customer-account.order-status.block.render"
module = "./src/OrderStatusBlock.tsx"

[[extensions.targeting]]
target = "customer-account.order.action.menu-item.render"
module = "./src/OrderActionMenuItem.tsx"
